### ISSUE TITLE
citizenIDs not working

### ISSUE THREAD

**Issue by Holidayy95** [overextended/ox_doorlock#104]
I've put my characters Citizenid into the Characters part, created the door, and it still says I cannot unlock it.

my citizenids length is 7 (if that matters). Both are up-to-date with the latest.

https://i.imgur.com/HMBSyl9.png

https://i.imgur.com/UwmXyHR.png

No errors or anything

**Comment by Manason** [comment]
This is likely related to https://github.com/overextended/ox_doorlock/pull/79/files/9117546ae5465df13b061b03cda0b4b18acfa3bb#r1002660669

I'm guessing this is only broken since you've modified QB to use only numbers in your citizenids rather than the default of starting with letters.

**Comment by LukeWasTakenn** [comment]
@Holidayy95 Can you try the latest commit with the `getCore` drop and see if the same still happens?

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/215980462-cae3b461-2f89-4f27-9f33-394b0d3aa49c.png)

**Comment by LukeWasTakenn** [comment]
0 activity on the issue and doesn't even seem to be an issue.
