### ISSUE TITLE
Error with the new esx 1.9 version

### ISSUE THREAD

**Issue by Badaasaaur** [overextended/ox_doorlock#107]
Can you please help me whith this error:
![image](https://user-images.githubusercontent.com/74657966/210008089-12a84207-fa0c-4cbb-a0fa-cd4d9b0c0939.png)

**Comment by paarbo** [comment]
I also have this error, with both 1.8.5 and 1.9.0 with the latest versions of ox

**Comment by LukeWasTakenn** [comment]
Start ox_target before starting ox_doorlock.
