### ISSUE TITLE
Command doorlock not working

### ISSUE THREAD

**Issue by LudiYoutuber65** [overextended/ox_doorlock#109]
![image](https://user-images.githubusercontent.com/67953605/210254739-a97a1241-fea7-4225-8830-416c9775cddb.png)
When I type the doorlock command, no nui pops up at all, just a mouse arrow pops up

**Comment by LukeWasTakenn** [comment]
Download release not source code.

**Comment by LudiYoutuber65** [comment]
> Download release not source code.

I downloaded the release

**Comment by N-fire** [comment]
> > Download release not source code.
> 
> I downloaded the release

no you didn't, download this :
![image](https://user-images.githubusercontent.com/55892717/210256085-03b11259-d97b-48fb-a25d-2166b63df15f.png)
