### ISSUE TITLE
[Suggestion] API Improvements

### ISSUE THREAD

**Issue by ghost** [overextended/ox_doorlock#11]
Some more API integrations such as editing authorization via API so people can more easily add authorizations to the script.

Example:
```lua
exports.ox_doorlock:editAuthorization('passcode', 'newCode')
exports.ox_doorlock:editAuthorization('groups', {'newgroups'})
```
I'll leave implementation up to someone who isn't a spud like me. but some door editing/authorization editing.

**Comment by thelindat** [comment]
What's the use case / benefit of doing this through exports vs the editor?

**Comment by ghost** [comment]
Being able to edit doors at runtime via code, for use with like gang
scripts or w/e to whitelist a certain group when they take over an area for
example.

**Comment by thelindat** [comment]
Added `exports.ox_doorlock:editDoor`, untested for my convenience.
Send the existing door id and a table containing key value pairs to modify.
