### ISSUE TITLE
Door password is not working

### ISSUE THREAD

**Issue by rocketich** [overextended/ox_doorlock#121]
I set the password of a door, but I can open the door with any password.

**Comment by LukeWasTakenn** [comment]
![image](https://user-images.githubusercontent.com/39926192/221407338-36eeed58-4d5c-4692-b39a-871c50a71884.png)
![image](https://user-images.githubusercontent.com/39926192/221407362-2a99fc23-2692-4734-a85e-c7bf8238a94b.png)
![image](https://user-images.githubusercontent.com/39926192/221407375-b77aa7bf-748a-4ae6-ae2a-e44bab85c71b.png)
