### ISSUE TITLE
Feature: Grouping Up MultipleLocks in "Buildings" so that a new Lock of a Building can easy be set up with the same settings

### ISSUE THREAD

**Issue by wofnull** [overextended/ox_doorlock#122]
Hello, 

a littlebit beforehand information to the background of my request:

It would be nice to get a sort of "Grouping Function" , so that multiple doorlocks can be grouped to a building, which defines the preset doorsettings for every door.

Example: Hotel / Hospital with many rooms.
Instead of setting up every lock for specific groups / door settings and so on, we define the settings for  the building in the "building group" and only choose the building group while creating a doorlock, which then automaticly gets all predefined access groups / identifiers / items preset.

In this way adding and of course later removing / changing access to a set of doors is way easyer and much less time consuming. Furthermore on a large set of doors, this simplyfies errorfinding with wrongly set settings for specific doors or many if needed to be corrected.

**Comment by thelindat** [comment]
I'm not going to outright say no, but this isn't something that'll be worked on soon.

You can already copy and paste settings from an existing door, and removing a group of doors is as easy as dropping rows from the database by using their names with wildcards if you used a naming scheme (sure, not as quick and easy as an interface).
