### ISSUE TITLE
Open a door for everyone

### ISSUE THREAD

**Issue by Bulle93230** [overextended/ox_doorlock#127]
Hi
We can now set a job (or some jobs) to be able to open a door.

My suggestion:
Add something to set ALL jobs
If i want everyone to be able to open a door, i have to enter all jobs one by one, it's really long

Thanks

**Comment by LukeWasTakenn** [comment]
What? That makes no sense.

Just don't define any jobs.

**Comment by thelindat** [comment]
> Just don't define any jobs.

Right now you have to define some form of authorisation; though what's the need to have doors that everyone can use anyway?

**Comment by Bulle93230** [comment]
> > Just don't define any jobs.
> 
> Right now you have to define some form of authorisation; though what's the need to have doors that everyone can use anyway?

I understand the trouble, for garages doors, it can be usefull to choose a speed to open/close, an autolock interval...
It can add a small amount of Role Play
Thanks
