### ISSUE TITLE
Doorpin dosnt work

### ISSUE THREAD

**Issue by Gametake** [overextended/ox_doorlock#129]
An exemple if i put the pin "1234" and save the door it save it and if i want to unlock the door work with any pin. I will attach an video for this if it needs.

**Comment by Gametake** [comment]
https://www.mediafire.com/file/t4or3vyivtz5hup/2023-03-19_15-45-23.mp4/file

**Comment by LukeWasTakenn** [comment]
Does your character have the police job you've set onto the door in the video?

**Comment by Gametake** [comment]
Yes

**Comment by thelindat** [comment]
https://github.com/overextended/ox_doorlock/commit/9daf3d4e33b8809aa2c76bbbf48f48e47ebb37ea
