### ISSUE TITLE
Stuck in UI, when picking lock and pressing E for unlocking door

### ISSUE THREAD

**Issue by Parz1val2045** [overextended/ox_doorlock#135]
When you pick lock and have access to the door and press E, sometimes you get stuck in the passcode Ui and need to relog to get out of it

**Comment by LukeWasTakenn** [comment]
"Sometimes" isn't good enough, going to need a consistent way to reproduce the issue.

You're also the only person to have reported this so far so a video showcasing the issue would also be helpful.
