### ISSUE TITLE
license identifier dont work if it starts with a number

### ISSUE THREAD

**Issue by LupusMaveTTV** [overextended/ox_doorlock#139]
if a license:identifier starts with a number, every string breaks and only the number is saved to database.

i.e: identifier: "f410b41b3e3e6af615bc0e4......." everything's fine, it starts with a "f", the whole string is updating to db-table,
identifier: "410b41b3e3e6af615bc0e4......." it starts with a "4", the string breaks at start of the first "b". only "410" is updating to db-table

**Comment by LukeWasTakenn** [comment]
This *should* be resolved with commit https://github.com/overextended/ox_doorlock/commit/20f6f0cd218d803293aaaeb9041d8a9789ad5adf.

Can you download the source code, build the UI, test it out and let us know whether it's fine now?

**Comment by LupusMaveTTV** [comment]
Sorry,i dont know, how to compile :D

**Comment by LukeWasTakenn** [comment]
> Sorry,i dont know, how to compile :D

Exact same process:
<https://overextended.github.io/docs/ox_lib/#building-the-ui>

**Comment by LukeWasTakenn** [comment]
Due to the lack of feedback I'll assume the issue has been resolved.
