### ISSUE TITLE
[Suggestion] Item metadata

### ISSUE THREAD

**Issue by N-fire** [overextended/ox_doorlock#14]
It would be nice to have the possibility to unlock a door with an item with specific metadata

**Comment by thelindat** [comment]
This would require supporting items as an object rather than an array.
Would allow for checking metadata for ox and qb, as well as adding an option to remove the item on use.

@LukeWasTakenn

**Comment by LukeWasTakenn** [comment]
That would be a few more UI elements, the items page would probably have to be designed differently to accommodate the third field which would be metadata, as 3 columns of fields might be a bit much.

Then also a checkbox for remove on use.

Not sure.

**Comment by thelindat** [comment]
> That would be a few more UI elements, the items page would probably have to be designed differently to accommodate the third field which would be metadata, as 3 columns of fields might be a bit much.
> 
> Then also a checkbox for remove on use.
> 
> Not sure.

How about keeping it simple and just
{[item] = metadata}

Item removal can be handled as an event already, so it’d be more about convenience having it built in; metadata support is less of a luxury.

**Comment by LukeWasTakenn** [comment]
> How about keeping it simple and just
{[item] = metadata}

We should probably just do a object with properties instead, doing it like this will make it really difficult to add onto the item options in the future.
