### ISSUE TITLE
UI Not Being Reset Between Doors

### ISSUE THREAD

**Issue by ghost** [overextended/ox_doorlock#143]
After creating a few doors with a few different options and opening to edit some of the doors going to another door keeps some of the options of the previous door.

Repro Steps
1. make a few doors with different settings (automatic, hold open, etc) (2 should work but my testing was with 6)
2. open one of your doors to edit it
3. exit out and open another door that has different settings.
4. see the settings from the previous door being applied in the UI of the door you're currently editing.

This only seems to affect the UI and doesn't actually affect the doors even after clicking save.

**Comment by LukeWasTakenn** [comment]
Should be resolved with 45acaea62c5abc2edfa34f2dabdd26a344dd16ff.

Can you download the source code, build the UI and test it out please?

**Comment by ghost** [comment]
That fixed it.
