### ISSUE TITLE
03.08.2023 SCRIPT ERROR after Update

### ISSUE THREAD

**Issue by NebelRebell** [overextended/ox_doorlock#157]
After Updates
ox_doorlock > v1.13.0
oxmysql > 2.7.3
ox_lib > 3.8.0
ox_target > 1.12.0

^1SCRIPT ERROR: 
@ox_doorlock/server/convert.lua:35: bad argument #1 to 'next' (table expected, got nil)^7
^1SCRIPT ERROR: 
@oxmysql/lib/MySQL.lua:31: First argument expected string, received 'nil'^7

**Comment by thelindat** [comment]
> @ox_doorlock/server/convert.lua:35: bad argument #1 to 'next' (table expected, got nil)^7

https://github.com/overextended/ox_doorlock/blob/87b3f0da5c5408a7c25fa0ec0176393fdb633573/server/convert.lua#L2

https://github.com/overextended/ox_doorlock/blob/87b3f0da5c5408a7c25fa0ec0176393fdb633573/server/convert.lua#L35

**Comment by NebelRebell** [comment]
[ox_doorlock/server/convert.lua
Config.DoorList = {} 
maybe
Config.DoorList = nil

ERROR FIX:
[ script:ox_doorlock] SCRIPT ERROR: @oxmysql/lib/MySQL.lua:31: First argument expected string, received 'nil'
