### ISSUE TITLE
SetDoorState problem(s)

### ISSUE THREAD

**Issue by TonybynMp4** [overextended/ox_doorlock#158]
The export setDoorState doesn't have a source passed to it, resulting in an error in isAuthorised because source is nil, the setState event is fine tho.
Also the export & event have different name, the docs are also incorrect for this as it lacks the event and has the wrong export name

**Comment by thelindat** [comment]
> the export & event have different name

Yes?

> docs are also incorrect for this as it lacks the event

To discourage use of the event.

> export setDoorState doesn't have a source passed to it

Right, forgot source defaults to nil and is only `''` when the event is triggered.

**Comment by TonybynMp4** [comment]
> > the export & event have different name
> 
> Yes?
> 
> > docs are also incorrect for this as it lacks the event
> 
> To discourage use of the event.

Well if it's intended then i guess it's ok 😄 thought it was a mistake or something
