### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Kekk0x** [overextended/ox_doorlock#2]
just to inform you I attach this error
![Desktop Screenshot 2022 04 07 - 22 00 47 80](https://user-images.githubusercontent.com/100416558/162286684-b28da30f-34b0-4f95-b6a6-e51e4f96f8ba.png)

**Comment by Shorty** [comment]
"Unable to load ox_core" - Means the script currently requires ox_core, you really shouldn't be using a WIP resource if you can't read errors.
