### ISSUE TITLE
[Bug]Menu doesnt popup

### ISSUE THREAD

**Issue by jordie058** [overextended/ox_doorlock#26]
I have the problem that the menu doesnt show up after u initilize the /doorlock command,
ox_doorlocks is started perfectly every dependency is installed and updated no issues on that end.

cant seem to find the error please help me.

Greetz.

**Comment by N-fire** [comment]
Download the release

**Comment by SimpleGamerDK** [comment]
I'm looking at this problem as well. If anyone has anything usefull to say please do so :)
And don't give us that "download the release" bullshit because that's excatly what I've done

**Comment by SimpleGamerDK** [comment]
On the forums just use the direct download link instead of the github link

**Comment by jordie058** [comment]
> On the forums just use the direct download link instead of the github link

this worked for me to open the menu now i have the following problem i can everything in i want i select the job thats autorized the little menu is working fine now when i open it with the command then i press submit and select with my qtarget the door i want to lock after that i press add doorlock the doorlock system closes the door but doesnt add the lock to it it stays unlocked and i cant find the issue...... it just doesnt upload it to my database or something i uploaded sql just fine.

**Comment by SimpleGamerDK** [comment]
> > On the forums just use the direct download link instead of the github link
> 
> this worked for me to open the menu now i have the following problem i can everything in i want i select the job thats autorized the little menu is working fine now when i open it with the command then i press submit and select with my qtarget the door i want to lock after that i press add doorlock the doorlock system closes the door but doesnt add the lock to it it stays unlocked and i cant find the issue...... it just doesnt upload it to my database or something i uploaded sql just fine.

The only problem I've got right now is that I can only add one door than the script completely fails and I have to restart it. So I add a door and everything works fine, than go to add another and my curser doesn't go off the screen and the console is full of errors.

**Comment by N-fire** [comment]
GitHub's issue are for bug report and suggestion, if you want to obtain support I suggest you to go to the overextended discord.
