### ISSUE TITLE
nothing appears on the screen

### ISSUE THREAD

**Issue by tonny766** [overextended/ox_doorlock#29]
Hello, thank you for the script, I have a problem.
When I type the command to create or edit a door, nothing appears on the screen. Thank you. (I'm on ESX)

**Comment by N-fire** [comment]
Download the **release** not the source code

**Comment by tonny766** [comment]
AHH Yes, sorry, now I get this error when I want to create a door = 

[  script:ox_doorlock] SCRIPT ERROR: @mysql-async/lib/MySQL.lua:12: Parameters should not be an array, but a map (key / value pair) instead

**Comment by N-fire** [comment]
Discord issue are for bug report and suggestion.
If you want some support I suggest you to ask in the overextended discord.
