### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by 2Beelzebub2** [overextended/ox_doorlock#31]
im trying to create a new door but I'm getting this error: SCRIPT ERROR: @mysql-async/lib/MySQL.lua:12: Parameters should not be an array, but a map (key / value pair) instead

**Comment by thelindat** [comment]
I'll just enforce oxmysql if people are going to be braindead and can't even use the latest _two year old version_ of mysql-async, which _does support array parameters_.

**Comment by 2Beelzebub2** [comment]
kinda new on this things sorry f it's a dumb question

**Comment by thelindat** [comment]
> kinda new on this things sorry f it's a dumb question

Yeah well I'm seeing a great influx of ESX 1.1 users who keep complaining about the same thing.

**Comment by 2Beelzebub2** [comment]
how can i fix it tho?

**Comment by thelindat** [comment]
> how can i fix it tho?

.....
![image](https://user-images.githubusercontent.com/65407488/172065966-61e7d720-2518-4a57-8c31-497e65147956.png)

**Comment by 2Beelzebub2** [comment]
will it be compatible with everything else?

**Comment by 2Beelzebub2** [comment]
where can i download it btw?

**Comment by thelindat** [comment]
> will it be compatible with everything else?

....

> where can i download it btw?

Where did you get it originally? Some fucking $100 ESX pack from fiverr?

**Comment by 2Beelzebub2** [comment]
it's a couple of scripts from here and there I don't know if it will affect some of them
