### ISSUE TITLE
Problem after creating doorlock :)

### ISSUE THREAD

**Issue by FurmaZ** [overextended/ox_doorlock#32]
![image](https://user-images.githubusercontent.com/69918985/172068391-b06749b7-6eeb-45f4-9666-e3182d0ae1b6.png)

**Comment by FurmaZ** [comment]
so everything works but I create one door and have to restart resource because I cant create another door.

**Comment by thelindat** [comment]
Update your qtarget.

**Comment by FurmaZ** [comment]
> Update your qtarget.

It worked thank you very much, and also amazing job you doing here I really appreciate that <3
