### ISSUE TITLE
Overflow scroll bar on 720p(1280x720) resolution.

### ISSUE THREAD

**Issue by meltynetv2** [overextended/ox_doorlock#42]
People running the doorlock on a 720p resolution, 1280x720 to be exact, they get a overflow scrollbar showing up on the right side of the screen. It can be fixed by putting a `overflow: hidden` on the css of the first "MuiBox-root" div.

I have the div selected in this picture to show you which div needs the css edit: https://i.gyazo.com/fcc2a690385c52bd6a54a38d8f626837.png

**Comment by LukeWasTakenn** [comment]
Will be resolved with the upcoming UI redesign (see dev branch).

**Comment by meltynetv2** [comment]
> Will be resolved with the upcoming UI redesign (see dev branch).

Great! Keep up the exceptional work!
