### ISSUE TITLE
Default groups over config

### ISSUE THREAD

**Issue by Zignixx** [overextended/ox_doorlock#44]
Hey,

after using doorlock for some weeks, we just had a idea to include a config setting to define "default groups".

Example: All our doors always include the groups: police, ambulance. So for every new door we need to add those groups at the beginning. 

It would be nice if there is a option to always include some groups while creating a new door! :)

Thank you

**Comment by thelindat** [comment]
Luke is working on the new UI, and I've already asked him to add in the clone/copy settings function.
