### ISSUE TITLE
Some door not work normally.

### ISSUE THREAD

**Issue by Racpy** [overextended/ox_doorlock#5]
example is sql file gabz_mrpd 6 and gabz_mrpd 7.
if i unlock and lock back, door return to normal position and show "Locked", but not correctly lock it.

**Comment by thelindat** [comment]
Probably not liking the heading, I may need to round the number.

Try using `/doorlock edit` and editing the door settings (should reset the heading, coords, etc).

**Comment by Racpy** [comment]
Now i'm using bf826cf49177d8137648f813da398a65f1bbd0ff
Some double door only work for a door. ( Example: gabz_mrpd 11 )
gabz_mrpd 28 is same model and double door work will. so confuse at this.

**Comment by thelindat** [comment]
I didn't touch door 11 or how door locking works _at all_.
If you're saying 11 worked before and not now, it's nothing to do with a change in this resource.


Door 11 is working completely fine with a _legit_ version of gabz mrpd (pre-escrow).

**Comment by Racpy** [comment]
I think i'm not using legit version (?)
Door 11 in sql default is set locked, If i unlock and leave mrpd some distance ( on legion garages ) then back to door 11,
door seems to work, but it just like block a door, not really locked two door, kick door still can open.

i think that's problem ( gabz_mrpd is provided by a friend, I'm not sure if it's legit. )
![image](https://user-images.githubusercontent.com/59442552/167369068-fd16ec08-ab8b-42d0-be5a-898e542c6243.png)
![image](https://user-images.githubusercontent.com/59442552/167373806-c7cc47bc-1003-4300-838c-d596dad7e842.png)

**Comment by thelindat** [comment]
> I think i'm not using legit version (?)

...

> i think that's problem ( gabz_mrpd is provided by a friend, I'm not sure if it's legit. )

It isn't, don't use it.
