### ISSUE TITLE
Error Loading Script

### ISSUE THREAD

**Issue by Noahv05** [overextended/ox_doorlock#54]
Hello,

I've been wanting to use ox_doorlock to make some locks on the gate at the airport.
Everytime in run the command I end up with this error.

Error loading script client/utils.lua in resource ox_doorlock: @ox_doorlock/client/utils.lua:115: No such export Object in resource qtarget
stack traceback:      	
[C]: in function 'error' citizen:/scripting/lua/scheduler.lua:878: in metamethod 'index'
          	@ox_doorlock/client/utils.lua:115: in main chunk

Thanks in advance!

**Comment by thelindat** [comment]
so start qtarget
