### ISSUE TITLE
Items remove not working

### ISSUE THREAD

**Issue by murayuki** [overextended/ox_doorlock#61]
The items deduction in the door lock setting is not working properly
I checked the items table and no remove exists

I checked the source code and found
https://github.com/overextended/ox_doorlock/blob/864723e87aed38ba28c8fd77659fc5eddbc0aebc/web/src/layouts/settings/Submit.tsx#L33

and changed this to
`if (!itemField.remove) itemField.remove = null;`

and build put it into the resource and it worked fine

I'm not sure if this is a real error

**Comment by LukeWasTakenn** [comment]
Can you submit a PR for this?
