### ISSUE TITLE
Make pls Citizen ID also to it

### ISSUE THREAD

**Issue by ghost** [overextended/ox_doorlock#63]
Because then it can replace the qb-doorlock scrtipt and it whould be a nice adding to it!

**Comment by LukeWasTakenn** [comment]
Citizen ID to also do what?

**Comment by ghost** [comment]
lock or unlock doors i mean i whould be nice to have some doors that only THESE PPL Can Open

**Comment by LukeWasTakenn** [comment]
As you can already do this using door passcodes, it's not something we are currently looking to support.
