### ISSUE TITLE
No such export in ox_lib from ox_doorlock

### ISSUE THREAD

**Issue by CeebDev** [overextended/ox_doorlock#64]
When connection to the server : 
- Check console F8
- There is error log about ox_lib export `SCRIPT ERROR: @ox_lib/init.lua:151: No such export cache in resource ox_lib`

All script work well it just log this in console

ox_lib : v2.11.1
ox_doorlock : v1.5.3

**Comment by LukeWasTakenn** [comment]
Most likely a global `.gitignore` file that ignores a `cache` directory, which is part of ox_lib.

**Comment by CeebDev** [comment]
Thanks you !

Yes i have cache directory in my .gitignore, i fix this to ignore only the cache folder at the root
