### ISSUE TITLE
Cannot open menu

### ISSUE THREAD

**Issue by thomasl92** [overextended/ox_doorlock#67]
When i try to open the doorlock menu via: /doorlock, it won't open.

When i open the FiveM console i got the following lines:
[     32485] [    GTAProcess]             MainThrd/ Error loading script client/utils.lua in resource ox_doorlock: @ox_doorlock/client/utils.lua:91: No such export addGlobalObject in resource ox_target
[     32485] [    GTAProcess]             MainThrd/ stack traceback:
[     32485] [    GTAProcess]             MainThrd/ 	[C]: in function 'error'
[     32485] [    GTAProcess]             MainThrd/ 	citizen:/scripting/lua/scheduler.lua:878: in metamethod 'index'
[     32485] [    GTAProcess]             MainThrd/ 	@ox_doorlock/client/utils.lua:91: in main chunk
[     32485] [    GTAProcess]             MainThrd/ Failed to load script client/utils.lua.

**Comment by LukeWasTakenn** [comment]
Make sure you are starting ox_target before starting ox_doorlock.

Also make sure you have the release (not the source code) and the required perms to open the UI.

**Comment by thomasl92** [comment]
"Make sure you are starting ox_target before starting ox_doorlock." fixed it.

Thanks!
