### ISSUE TITLE
OX_doorlock without ox_target

### ISSUE THREAD

**Issue by Eivor-dev** [overextended/ox_doorlock#69]
Do you think it is possible to make a version of this script without using ox target, qttarget etc?

**Comment by N-fire** [comment]
You only need it for door creation and lock pick beside that you don't need it.
You can create the door on an other server and add the to your db.

**Comment by thelindat** [comment]
Are you asking if it's possible, or are you asking _will you remove the dependence on targeting resources_? Two very different questions and _of course it's possible_; it's open-source and the world is your oyster.
