### ISSUE TITLE
Door's not locking every time

### ISSUE THREAD

**Issue by benzon** [overextended/ox_doorlock#71]
Hey,

So i have had quite abit of issues, with doors not locking, i have to leave the area before they will lock for me again, for others it locks like it should, it seems there might be a sync issue of some sort?

**Comment by N-fire** [comment]
Would be nice if you could provide a way to reproduce it consistently.

**Comment by LukeWasTakenn** [comment]
What version are you on? I swear there was an issue for this already which was resolved

**Comment by CeebDev** [comment]
Alone on my test server, with a lot of doorlock, sometimes i lock / unlock door and the door is lock on UI but not ingame, it's random 
i'm on last version

**Comment by LukeWasTakenn** [comment]
Seems to be related to #22 ?

**Comment by benzon** [comment]
@N-fire doing a repo is darn hard, but from what i have seen it tends to happen, if you have been around the doors for quite some time, suddenly they stop locking for you, and its 50/50 if they are locked for others.

@LukeWasTakenn Latest version.

**Comment by xDope7137** [comment]
I did indeed have the same issue. I was not able to reproduce it. But my community reported double doors not syncing and the sliding doors also.

I am going to to retry with the latest version soon in an update to see if I can catch something. 

But I can confirm it happens with double doors more then single doors.

**Comment by CeebDev** [comment]
I have the problem on simple door, but on all my doors i have automatic and double doors

**Comment by thelindat** [comment]
Dead issue / assumed resolved.
