### ISSUE TITLE
[Bug] Doorlocks failes after edit

### ISSUE THREAD

**Issue by benzon** [overextended/ox_doorlock#8]
Tested this a few times now.

If i edit doors the lock state messes up and im not able to lock the door again before i actually restart the doorlock script.

**Comment by thelindat** [comment]
I've edited doors a million times while in game without issue.
Is this if you edit the door while it isn't in its default state? Though, still unsure why the state would bug out.

**Comment by benzon** [comment]
ill try and test this out and document via a video.

**Comment by benzon** [comment]
Seems to work now
