### ISSUE TITLE
cant select locale

### ISSUE THREAD

**Issue by ghost** [overextended/ox_doorlock#82]
when you set your locale in fxmanifest.lua
it wont set it.

**Comment by N-fire** [comment]
Just by curiosity how did you set your locale in your fxmanifest ?

**Comment by ghost** [comment]
files {
	'web/build/index.html',
	'web/build/**/*',
	'locales/de.json'
}

Like here

**Comment by N-fire** [comment]
How yes that make sense, make sure to move this file in the server artifact.
