### ISSUE TITLE
Lockpick dont work anymore with 1.6.0

### ISSUE THREAD

**Issue by coresync2k** [overextended/ox_doorlock#83]
Hello,
 i updated to Version 1.6.0 and the lockpick function is not working anymore with 1.5.3 it is working.
 I got all other ressrouces updated to the latest.
 
 What i tested is simple, just add a door with /doorlock set to "locked and lockpick" give me the item "lockpick" and try to lockpick it with ox_target... but nothing shows up, then i downgrade to 1.5.3 and then its working.

**Comment by thelindat** [comment]
No idea how you tested and determined that a doorlock update broke lockpicks; you can even look through the commits and see _nothing was altered_.

This was an issue with qb support for ox_target.

https://github.com/overextended/ox_target/commit/76b797f627247427192a83c2d207a3e68f406144

**Comment by coresync2k** [comment]
yeah what should i say?

I use ESX, posted you what i was doing, and target dont accept the lockpick function on the door ... with 1.6.0 with the "older" version 1.5.3 it is working, nothing other changes were done.

**Comment by thelindat** [comment]
> I use ESX

Well you certainly never specified _what you use_, and you were using qb as recently as last month. You seem intent on leaving out information and, most importantly, an error.

**Comment by coresync2k** [comment]
iam sorry about it. i have created an thread on discord. ( https://discord.com/channels/813030955598086174/1035540334924542032 )

i will copy paste this in here for a better bug report.

I have ox_lib /inventory / ox_target and ox_doorlock in the newest release versions and use esx ( 1.8.5 )

So now to my Problem. I add a door called "lockpicktest" 
https://gyazo.com/672b1510bb3603b01c0d8b2e955c4cd7

i got the Item "lockpick" in my Inventory... now i go with "ox_target" to the Door and it lokes like this ...
https://gyazo.com/c51235213524b13e7a43c6b4ffbc39a8

so no "lockpick function there"
Now i downgrade to Version 1.5.3
and now the door Looks like this ...

https://gyazo.com/f4b4dd7ab6a6fdd2a95da7d872acead6

Lockpicking is working ...

here the door with 1.5.3 
https://gyazo.com/29dafc584fa2a3dd292033e15960f14f

**Comment by thelindat** [comment]
> iam sorry about it. i have created an thread on discord.

Yes, I saw it; and still no error. The fact the debug option doesn't even display on the door means something threw an error before sending to ox_doorlock nui.

There's _still nothing_ that changed in this resource that would have or could have broken lockpicks.

https://github.com/overextended/ox_doorlock/compare/v1.5.3...v1.6.0

**Comment by coresync2k** [comment]
Yes, I've seen the changes and I can't explain what's causing the whole thing, but if I just only change the doorlock and it works..

dont know, i can change the ressources on the fly and doorlock 1.5.3 will be working and 1.6.0. not ( and no i dont have done that ) just only in my test purposes... 

can i do anything to give more details or something?

client side F8 and Serverconsole are fine, no errors at all :/

**Comment by coresync2k** [comment]
> The fact the debug option doesn't even display on the door means something threw an error before sending to ox_doorlock nui.

yeah, but what? and why only in 1.6.0 and not in 1.5.3 ? thats what i dont understand.

**Comment by thelindat** [comment]
Alternatively, you're _doing something_ beyond "just changing the version of ox_doorlock".
I've just fixed a bug _in ox_target_ where options were being removed incorrectly, which is more likely to be what you're experiencing (and still nothing to do with your weird "1.6.0 no work" narrative).

**Comment by coresync2k** [comment]
I will test it now, with 1.6.0 and the new target, and i dont say it MUST be doorlock, but it is only the thing that i changed nothing else

**Comment by coresync2k** [comment]
okay, it works. with the new target and 1.6.0

so the issue can be closed, im sorry if i was in the wrong ressource.

thx for your help and fixing it.
