### ISSUE TITLE
Cant add new gates in some places.

### ISSUE THREAD

**Issue by FurmaZ** [overextended/ox_doorlock#88]
![image](https://user-images.githubusercontent.com/69918985/199961297-2c54d10b-449f-4edb-bcf7-7d4d467772f3.png)
maybe someone have same problem.
most of the gates are addible but like one from gabz sandy shores just impossible to add

**Comment by thelindat** [comment]
If you still haven't resolved, update either your qtarget or (more likely) qb-target.
