### ISSUE TITLE
Character id?

### ISSUE THREAD

**Issue by Infalx** [overextended/ox_doorlock#89]
Im running a qbcore based server and was wondering what ID I would need specifically to assign a door to someone?

**Comment by thelindat** [comment]
citizenid

**Comment by Infalx** [comment]
> 

Do you know where I can find it?

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/201504755-60f74c0a-0a1b-42ab-9a85-4ac72a29bb39.png)
