### ISSUE TITLE
Doors don't auto close when locking

### ISSUE THREAD

**Issue by Xoogle5M** [overextended/ox_doorlock#90]
When going through a door and locking it while you walk through, the door often remains opened although it shows that it is locked.

Is there a way to make it automatically lock back into the doorframe again without using the auto lock option?

**Comment by thelindat** [comment]
See
- https://github.com/overextended/ox_doorlock/issues/22
- https://github.com/overextended/ox_doorlock/issues/71
- https://github.com/overextended/ox_doorlock/issues/81
