### ISSUE TITLE
After completing the doorlock gui nothing happens

### ISSUE THREAD

**Issue by ilveopensource** [overextended/ox_doorlock#91]
**Goodmorning**, I installed this script on my server with ox_lib release up to date then  installed ox_target last release too. I already had oxmysql installed. 

I run /doorlock
The doorlock ui shows after the command /doorlock
I complete the form then sumbit
The GUI disappears and nothing else appear, if I run /doorlock again it doesn't work and I see no serverside error and no clientside error.
Am I doing something wrong? I also tried removing ox_target and tried to use qtarget but nothing changed.

Any help is appreciated! 
![This is an image](https://www.apple.com/newsroom/images/values/health/standard/Apple_Heart-health-update_Flowerheart_inline.gif.small_2x.gif)

**Comment by N-fire** [comment]
You should ask in the overextended discord.
