### ISSUE TITLE
Problem with building file

### ISSUE THREAD

**Issue by FUst1ke** [overextended/ox_doorlock#92]
Helo!
I have a problem which happened today like 30 mins ago, the thing is I built the files inside the web folder with npm i then npm run build ready, I installed it to my server but when I joined to the server, the screen was grey! I downloaded again, did it again but the same issue stays and I don't think it is my problem so please fix it till midnight because I really need it to be fixed to work on with my project thank you for your time to read my issue and I hope it will be easy to fix it thank you very much Gellipapa sends his regards!

Good night!

**Comment by LukeWasTakenn** [comment]
Download release not source code.

**Comment by FUst1ke** [comment]
I know that I have to download the source code, but I added one feature for myself then I built it, but I tried it how you say and it didn't worked well either. Don't close it as you read it, try to look up for the problem thank you :)

**Comment by N-fire** [comment]
you should ask in the discord, github issue are for bug reports or suggestion.

**Comment by thelindat** [comment]
You’re using npm. We use pnpm.

**Comment by FUst1ke** [comment]
I solved the problem, thanks for the help. It works perfectly :) Sorry for the language.
