### ISSUE TITLE
Some doors cant not be taget

### ISSUE THREAD

**Issue by MiniFido** [overextended/ox_doorlock#94]
some doors ar not to betaget.
i have try over some time and the old system dit work fine.
some are glass doors and i normal i can go for the handel but not here.
and jail doors 
and it is GTA props. i have put the prop name of the doors i have shown here,

jail door
v_ilev_ph_cellgate
![218_20221122142319_1](https://user-images.githubusercontent.com/72674586/203326400-d87111ba-b60c-4bcb-823a-d76d719d663c.png)
![218_20221122142332_1](https://user-images.githubusercontent.com/72674586/203326402-4c2c5640-11e9-4a01-8b55-a7af5b1ddb32.png)
glass door
p_jewel_door_l
p_jewel_door_r1
![218_20221122142148_1](https://user-images.githubusercontent.com/72674586/203326398-743d2fe5-0578-42fc-9916-c081829ba0eb.png)

![218_20221122142120_1](https://user-images.githubusercontent.com/72674586/203326407-8fe12e33-f899-4734-bc60-a7acf1489fe1.png)

this is just to show that it normalt works
![218_20221122142129_1](https://user-images.githubusercontent.com/72674586/203326392-49f1f10a-6ef0-415c-bcbd-ed101f2efe28.png)

**Comment by LukeWasTakenn** [comment]
Duplicate of #88

**Comment by MiniFido** [comment]
works whit update
