### ISSUE TITLE
garage doors not closing on lock 

### ISSUE THREAD

**Issue by UwUway** [overextended/ox_doorlock#97]
we updated to the most recent update, now garage doors will not close the actual prop when locked, it'll keep it locked if you come to the area but not when you're at it. 
![image](https://user-images.githubusercontent.com/111474428/205155096-8b625e5f-1de7-4c5d-929e-c6f055256236.png)

**Comment by Manason** [comment]
This issue appears to be limited to MLO doors and related to commit [4dd4ccf8](https://github.com/overextended/ox_doorlock/commit/4dd4ccf8ba79811d30438e10ca10f374b336bd70).

[Video with 4dd4ccf8](https://medal.tv/games/gta-v/clips/LbFbKc8S-xux2/d1337589QHvj?invite=cr-MSx5d0IsNTUzNTcwMSw)

[Video reverting 4dd4ccf8](https://medal.tv/games/gta-v/clips/LbGqFC2vDgIi2/d1337VnYHyS6?invite=cr-MSxZYzMsNTUzNTcwMSw)

**Comment by thelindat** [comment]
Did you set the door as automatic? Can’t be bothered checking right now but I’m pretty sure it’s only used for that heading check; which won’t work on sliding and rolling doors.

**Comment by Manason** [comment]
Door was not on auto. Switching it to auto fixes the issue.
