### ISSUE TITLE
Your Translations are not working?

### ISSUE THREAD

**Issue by ghost** [overextended/ox_doorlock#99]
why does it say "Translation for unlocked_door not found

**Comment by LukeWasTakenn** [comment]
What?

**Comment by ghost** [comment]
exact what i say i try to set in the fxmanifest locales/de.json
not working

**Comment by LukeWasTakenn** [comment]
You need to set the `ox:locale` convar, not add the file in the fxmanifest.

<https://overextended.github.io/docs/ox_lib/Locale/Shared/>

**Comment by ghost** [comment]
Oh haha sry and Thanks for help!
